### ISSUE TITLE
How to use the wasm32 CPU target

### ISSUE THREAD

**Issue by yagehu** [bazelbuild/platforms#18]
#12 adds the wasm32 CPU. But when I try to use it in my project, I get:

```
ERROR: /home/huyage/dev/wasm/wasmbench/platforms/BUILD.bazel:9:9: no such target '@platforms//cpu:wasm32': target 'wasm32' not declared in package 'cpu' defined by /home/huyage/.cache/bazel/_bazel_huyage/82c2da1739c371e7ca0d69f58318b066/external/platforms/cpu/BUILD and referenced by '//platforms:wasm32'
```

I'm on the latest Bazel version using bazelisk.

**Comment by aiuto** [comment]
There is not enough information here to say anything. Can you create a small repo.

**Comment by yagehu** [comment]
I'm not working with Bazel anymore. So I'll close this issue.
